api/urls.py
from django.conf.urls import url, patterns

from . import views


urlpatterns = patterns('',
    url(r'^company/$', views.CompanyList.as_view()),
    url(r'^company/(?P<pk>\d+)/$', views.CompanyDetailApi.as_view()),
    url(r'^company/(?P<pk>\d+)/events/$', views.CompanyEventList.as_view()),
)

coming_soon/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url('^$', views.Index.as_view()),
)

company/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.user_dashboard, name='dashboard'),
    url(r'^detail/(?P<pk>\d+)/$', views.company_detail, name='detail'),
)

social_company/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'social_company.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('coming_soon.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^docs/', include('rest_framework_swagger.urls')),
)

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

api/models.py
from django.db import models

# Create your models here.

coming_soon/models.py
from django.db import models

# Create your models here.

company/models.py
from django.db import models
from django.contrib.auth.models import Group, User
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Company(Group):
    detail = models.TextField(blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Companies"
        ordering = ['name']

        permissions = (
            ('view_company', 'Is member of Company'),
        )

    def __str__(self):
        return '%s' % self.name


@python_2_unicode_compatible
class Event(models.Model):
    company = models.ForeignKey(Company)
    title = models.CharField(max_length=255)
    date = models.DateField()
    time = models.TimeField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = (
            ('view_event', 'Is member of Company'),
        )

    def __str__(self):
        return '%s - %s' % (self.title, self.date)

api/views.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework import filters
from .permissions import ViewPermissionOverride, DjangoObjectPermissionsOnly

from company.serializer import CompanySerializer, EventSerializer
from company.models import Company, Event


class CompanyList(generics.ListCreateAPIView):
    permission_classes = (ViewPermissionOverride,)
    serializer_class = CompanySerializer
    model = Company


class CompanyDetailApi(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (ViewPermissionOverride,)
    serializer_class = CompanySerializer
    model = Company


class CompanyEventList(generics.ListCreateAPIView):
    permission_classes = (ViewPermissionOverride,)
    serializer_class = EventSerializer
    model = Event

    def get_queryset(self):
        events = Event.objects.filter(company=self.kwargs['pk'])
        return events

coming_soon/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.


class Index(generic.TemplateView):
    template_name = 'coming_soon/index.html'

company/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from guardian.core import ObjectPermissionChecker

# Create your views here.


from django.shortcuts import render_to_response
from django.template import RequestContext
from .models import Company
from guardian.shortcuts import get_objects_for_user


def user_dashboard(request, template_name='company/index.html'):
    company = get_objects_for_user(request.user, 'company.view_company')

    return render_to_response(template_name, {'companies': company},
                              context_instance=RequestContext(request))


def company_detail(request, pk):
    company = Company.objects.get(id=pk)
    company_object = get_object_or_404(Company, pk=pk)
    template = 'company/public_detail.html'
    # check if user has permission to view, if so render private template
    if request.user.is_authenticated():
        user = request.user
        checker = ObjectPermissionChecker(user)
        if checker.has_perm('view_company', company):
            template = 'company/secure_detail.html'

    return render_to_response(template, {'company': company_object})


class CreateCompany(generic.CreateView):
    model = Company

coming_soon/templates/coming_soon/index.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}

{% block outside_container %}
<div class="jumbotron text-center">
<h1>Coming Soon!</h1>
<p>A Social Site for Companies.</p>
</div>
{% endblock %}
{% block content %}
<div class="row">
<div class="col-lg-12">
</div>
</div>
{% endblock %}

company/templates/company/index.html
{% extends 'base.html' %}
{% block content %}
<ul>
{% for company in companies %}
    <li><a href="{% url 'company:detail' company.id %}">{{ company }}</a> </li>
{% endfor %}
</ul>
{% endblock %}

company/templates/company/public_detail.html
{% extends 'base.html' %}
{% block content %}
{{ company }} Public
{% endblock %}

company/templates/company/secure_detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="page-header">{{ company }}</h1>
    Private
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    {% load staticfiles %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>
</head>
<body>
{% block nav %}
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'company:dashboard' %}">Social Company</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
{% endblock %}
{% block outside_container %}
{% endblock %}
<div class="container">
{% block content %}

{% endblock %}
</div>

{% block footer %}

{% endblock %}
<script src="{% static 'js/jquery-2.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/angular.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/angular-route.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/angular-resource.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/angular-animate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/django-rest-resource.js' %}" type="text/javascript"></script>
<script src="{% static 'js/angular-cookies.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/angular-filters.js' %}" type="text/javascript"></script>

{% block extra_js %}{% endblock %}

</body>
</html>